# SPDX-License-Identifier: MIT

# See "Full Tag Listing" in https://hub.docker.com/_/microsoft-windows-servercore
ARG WIN_VERSION=ltsc2022
FROM mcr.microsoft.com/windows/servercore:$WIN_VERSION AS MSYS2_download

# We always download x86_64 MSYS2 installer, since our system itself is x86_64.
ARG MSYS2_VERSION=20240507
ARG MSYS2_DOWNLOAD_URL=https://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-${MSYS2_VERSION}.sfx.exe
RUN setx /M PATH "C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%" && \
    powershell -Command "Invoke-WebRequest -Uri %MSYS2_DOWNLOAD_URL% -OutFile C:\windows\temp\msys2-base.sfx.exe"  && \
    C:\windows\temp\msys2-base.sfx.exe x -o"C:"
# NOTE: workaround for "gpg: error reading key: Connection timed out"
RUN bash -l -c "exit 0"
RUN bash -l -c "pacman -Syuu --noconfirm --noprogressbar"  && \
    bash -l -c "pacman -Syu --needed --noconfirm --noprogressbar"  && \
    bash -l -c "pacman -Syu --needed --noconfirm --noprogressbar"  && \
    bash -l -c " \
        pacman -S --needed --noconfirm --noprogressbar \
            mingw-w64-i686-cmake diffutils git m4 make patch tar p7zip curl python3 \
        "  && \
    bash -l -c "git config --system core.longpaths true" && \
    bash -l -c "pacman -Scc --noconfirm"  && \
    echo ---- [%date% %time%] Pkg install done!
# NOTE: If you hang here >10 min. You may want to `zap` temp files.
#   ref: https://github.com/msys2/MSYS2-packages/issues/2305#issuecomment-758162640

# The C/C++/Fortran toolchain is not MSYS2's, but GCCToolchain_jll (Yggdrasil's
# `G/GCCToolchain`): GCC 15.2 built exactly like the GCC that CompilerSupportLibraries_jll
# comes from, whose runtime DLLs Julia ships (with SJLJ exceptions on i686). Installed in
# its own prefix, C:\gcc, ahead of MSYS2's in PATH; MSYS2's own programs keep loading the
# DLLs next to them.
# Bump only together with CompilerSupportLibraries_jll's GCC.
ARG GCC_TOOLCHAIN_URL=https://github.com/JuliaBinaryWrappers/GCCToolchain_jll.jl/releases/download/GCCToolchain-v15.2.0+1/GCCToolchain.v15.2.0.i686-w64-mingw32.tar.gz
ARG GCC_TOOLCHAIN_SHA256=28DFE67262C82D9D1F277DE2363CB47A363A393F76176070F76A49B9E8CA8547
RUN powershell -Command "\
        Invoke-WebRequest -Uri '%GCC_TOOLCHAIN_URL%' -OutFile C:/windows/temp/gcc.tar.gz -ErrorAction Stop ; \
        if ((Get-FileHash -Algorithm SHA256 C:/windows/temp/gcc.tar.gz).Hash -ne '%GCC_TOOLCHAIN_SHA256%') { throw 'GCCToolchain checksum mismatch' }" && \
    mkdir C:\gcc && \
    bash -l -c "tar -xzf /c/windows/temp/gcc.tar.gz -C /c/gcc && rm /c/windows/temp/gcc.tar.gz" && \
    bash -l -c "PATH=/c/gcc/bin:$PATH; gcc --version && echo 'int main(void){return 0;}' > /tmp/t.c && gcc /tmp/t.c -o /tmp/t.exe && /tmp/t.exe"

# ---- Move to new container, to drop messy build history
ARG WIN_VERSION=ltsc2022
FROM mcr.microsoft.com/windows/servercore:$WIN_VERSION

COPY --from=MSYS2_download C:/msys64 C:/msys64
COPY --from=MSYS2_download C:/gcc C:/gcc

# Install .NET runtime for i686
ARG DOTNET_URL="https://download.visualstudio.microsoft.com/download/pr/c2083daf-6d33-404f-a7d6-dd3bb012a945/e241d0aff000f63ef8a49c3c7da08087/dotnet-runtime-8.0.8-win-x86.exe"
ARG DOTNET_EXE="C:/windows/temp/dotnet-runtime.exe"
RUN powershell -Command "\
    Invoke-WebRequest -Uri '%DOTNET_URL%' -OutFile '%DOTNET_EXE%' -ErrorAction Stop ; \
    Start-Process '%DOTNET_EXE%' -Wait -ArgumentList '/install', '/quiet', '/norestart' ; \
    Remove-Item '%DOTNET_EXE%'"

# Download Windows 11 SDK (10.0.22621.2428) and install only `signtool.exe`
ARG SDK_URL="https://go.microsoft.com/fwlink/?linkid=2250105"
ARG SDK_EXE="C:/windows/temp/winsdksetup.exe"
RUN powershell -Command "\
        Invoke-WebRequest -Uri '%SDK_URL%' -OutFile '%SDK_EXE%' -ErrorAction Stop ; \
        Start-Process '%SDK_EXE%' -Wait -ArgumentList '/features OptionId.SigningTools', '/q', '/ceip off', '/norestart' ; \
        setx /M PATH ('%PATH%;' + (Resolve-Path 'C:/Program Files (x86)/Windows Kits/10/bin/*/x64/')) ; \
        Remove-Item '%SDK_EXE%'"

# Install Visual C++ redistributables
RUN powershell -Command "Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force; Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name VcRedist -SkipPublisherCheck -Force -ErrorAction Stop"

# Install AWS CLI
RUN msiexec.exe /i "https://awscli.amazonaws.com/AWSCLIV2.msi" /quiet /qn && \
    setx /M PATH "%PATH%;C:\Program Files\Amazon\AWSCLIV2"

# Install `TrustedSigning` powershell module
RUN powershell -Command "Install-Module -Name TrustedSigning"


# Set default environment variables and setup useful symlinks
# Note that we add an entry for `buildkite-agent` here despite it not being within
# the image, because we expect it to be mounted within us in the future.
RUN setx /M PATH "C:\buildkite-agent\bin;C:\gcc\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%" && \
    mklink /J  C:\msys64\home\ContainerUser C:\Users\ContainerUser  && \
    setx /M  HOME C:\msys64\home\ContainerUser
WORKDIR C:/home/ContainerUser

# Select the mingw64 environment: https://www.msys2.org/docs/environments/
ENV MSYSTEM=MINGW64

# Default to `bash` for interactive builds
CMD ["bash"]
