name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # Build a bunch of different "agent" rootfs images.
          # ppc64le pending: https://github.com/buildkite/agent/issues/1472
          - 'buildkite_agent_linux.aarch64'
          - 'buildkite_agent_linux.armv7l'
          # - 'buildkite_agent_linux.ppc64le'
          - 'buildkite_agent_linux.x86_64'

          # The `package_linux` images are all `debian`-based.
          - 'package_linux.aarch64'
          - 'package_linux.armv7l'
          - 'package_linux.i686'
          - 'package_linux.powerpc64le'
          - 'package_linux.x86_64'

          # The `package_musl` image is `alpine`-based.
          - 'package_musl.x86_64'

          # The `tester_linux` images are all `debian`-based.
          # They do not include the compiler toolchain.
          - 'tester_linux.aarch64'
          - 'tester_linux.armv7l'
          - 'tester_linux.i686'
          - 'tester_linux.powerpc64le'
          - 'tester_linux.x86_64'

          # The `tester_musl` image is `alpine`-based.
          # It does not include the compiler toolchain.
          - 'tester_musl.x86_64'

          # The `llvm_passes` image is a short-term solution for the `analyzegc` builder.
          - 'llvm_passes.x86_64'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          arch: x64
      - run: sudo apt-get update
      - run: |
          sudo apt-get -y install binfmt-support debootstrap qemu-user-static
      - run: julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --color=yes --project=. -e 'using Pkg; Pkg.precompile()'
      - run: |
          IMAGE_NAME=$(echo ${{ matrix.image }} | cut -d. -f1)
          IMAGE_ARCH=$(echo ${{ matrix.image }} | cut -d. -f2)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_ARCH=$IMAGE_ARCH" >> $GITHUB_ENV
      - run: julia --color=yes --project=. images/${{ env.IMAGE_NAME }}.jl --arch=${{ env.IMAGE_ARCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
