name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - 'buildkite_agent'
          - 'llvm_passes'
          - 'package_linux64'
          - 'package_musl64'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          arch: x64
      - run: sudo apt-get update
      - run: sudo apt-get -y install debootstrap
      - run: julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --color=yes --project=. -e 'using Pkg; Pkg.precompile()'
      - run: julia --color=yes --project=. images/${{ matrix.image_name }}.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
