name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  all:
    name: all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "All build jobs have completed."
  build:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # Build a bunch of different "agent" rootfs images.
          - 'agent_linux.aarch64'
          - 'agent_linux.armv7l'
          - 'agent_linux.ppc64le'
          - 'agent_linux.x86_64'

          # The `debian_minimal` image is a `debian`-based image that
          # contains no packages.
          - 'debian_minimal.x86_64'

          # The `package_linux` images are all `debian`-based.
          - 'package_linux.aarch64'
          - 'package_linux.armv7l'
          - 'package_linux.i686'
          - 'package_linux.powerpc64le'
          - 'package_linux.x86_64'

          # The `package_musl` image is `alpine`-based.
          - 'package_musl.x86_64'

          # The `tester_linux` images are all `debian`-based.
          # They do not include the compiler toolchain.
          - 'tester_linux.aarch64'
          - 'tester_linux.armv7l'
          - 'tester_linux.i686'
          - 'tester_linux.powerpc64le'
          - 'tester_linux.x86_64'

          # The `tester_musl` image is `alpine`-based.
          # It does not include the compiler toolchain.
          - 'tester_musl.x86_64'

          # The `llvm_passes` image is a short-term solution for the `analyzegc` builder.
          - 'llvm_passes.x86_64'

          # The `pkgserver_logsync` image is a helper for https://github.com/JuliaPackaging/PkgServerLogAnalysis.jl
          - 'pkgserver_logsync.x86_64'
    steps:
      - uses: actions/checkout@v2
      - run: echo The head ref is ${{ github.head_ref }}
      - run: echo The ref is ${{ github.ref }}
