name: Whitespace
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  whitespace:
    name: whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git status
      - name: Check whitespace
        run: |
          set -Eeuo pipefail
          echo "Checking for whitespace issues..."
          if git --no-pager grep --color -n --full-name -e ' $' -- *
          then
            echo "Error: trailing whitespace found in source file(s)"
            echo ""
            echo "This can often be fixed with:"
            echo "    git rebase --whitespace=fix HEAD~1"
            echo "or"
            echo "    git rebase --whitespace=fix master"
            echo "and then a forced push of the correct branch"
            exit 1
          else
            echo "Whitespace check found no issues"
          fi
        shell: bash
